insert into student (first_name, last_name, eag, email) values ('Lalo', 'Beernt', 2007, 'lbeernt0@rediff.com');
insert into student (first_name, last_name, eag, email) values ('Alisun', 'Cronin', 1995, 'acronin1@sakura.ne.jp');
insert into student (first_name, last_name, eag, email) values ('Waly', 'Demkowicz', 2011, 'wdemkowicz2@cnbc.com');
insert into student (first_name, last_name, eag, email) values ('Tomaso', 'Sennett', 2002, 'tsennett3@ebay.com');
insert into student (first_name, last_name, eag, email) values ('Joya', 'Louys', 1987, 'jlouys4@virginia.edu');
insert into student (first_name, last_name, eag, email) values ('Freddy', 'Wabe', 2004, 'fwabe5@xing.com');
insert into student (first_name, last_name, eag, email) values ('Bobbie', 'Lambshine', 2010, 'blambshine6@spotify.com');
insert into student (first_name, last_name, eag, email) values ('De witt', 'Bernardez', 1995, 'dbernardez7@about.me');
insert into student (first_name, last_name, eag, email) values ('Farica', 'Begin', 2012, 'fbegin8@npr.org');
insert into student (first_name, last_name, eag, email) values ('Stefan', 'Woolager', 1979, 'swoolager9@cornell.edu');
insert into student (first_name, last_name, eag, email) values ('Sayre', 'Nyland', 1999, 'snylanda@independent.co.uk');
insert into student (first_name, last_name, eag, email) values ('Freda', 'Grenter', 1998, 'fgrenterb@bandcamp.com');
insert into student (first_name, last_name, eag, email) values ('Morse', 'Straine', 2003, 'mstrainec@twitter.com');
insert into student (first_name, last_name, eag, email) values ('Bonni', 'Habbergham', 2004, 'bhabberghamd@google.cn');
insert into student (first_name, last_name, eag, email) values ('Cherry', 'Fawke', 1999, 'cfawkee@google.com.hk');
insert into student (first_name, last_name, eag, email) values ('Humphrey', 'Waryk', 2002, 'hwarykf@netlog.com');
insert into student (first_name, last_name, eag, email) values ('Jeremias', 'Liff', 1988, 'jliffg@vimeo.com');
insert into student (first_name, last_name, eag, email) values ('Barty', 'Moncaster', 2006, 'bmoncasterh@cnbc.com');
insert into student (first_name, last_name, eag, email) values ('Salomo', 'Mathe', 1991, 'smathei@slashdot.org');
insert into student (first_name, last_name, eag, email) values ('Chrissy', 'Outridge', 2008, 'coutridgej@craigslist.org');
insert into student (first_name, last_name, eag, email) values ('Grant', 'Sweeny', 2012, 'gsweenyk@altervista.org');
insert into student (first_name, last_name, eag, email) values ('Taddeusz', 'Plewman', 2007, 'tplewmanl@umn.edu');
insert into student (first_name, last_name, eag, email) values ('Bradley', 'Cultcheth', 2013, 'bcultchethm@sourceforge.net');
insert into student (first_name, last_name, eag, email) values ('Gerardo', 'Carayol', 2002, 'gcarayoln@angelfire.com');
insert into student (first_name, last_name, eag, email) values ('Celestia', 'Chaves', 2009, 'cchaveso@washington.edu');
insert into student (first_name, last_name, eag, email) values ('Bearnard', 'Knightsbridge', 1989, 'bknightsbridgep@bbc.co.uk');
insert into student (first_name, last_name, eag, email) values ('Haley', 'MacConnal', 2003, 'hmacconnalq@thetimes.co.uk');
insert into student (first_name, last_name, eag, email) values ('Hermia', 'Crinkley', 2002, 'hcrinkleyr@printfriendly.com');
insert into student (first_name, last_name, eag, email) values ('Purcell', 'Poile', 2001, 'ppoiles@wunderground.com');
insert into student (first_name, last_name, eag, email) values ('Andromache', 'Redholls', 1988, 'aredhollst@census.gov');
insert into student (first_name, last_name, eag, email) values ('Maxim', 'Mainwaring', 2003, 'mmainwaringu@phoca.cz');
insert into student (first_name, last_name, eag, email) values ('Chloette', 'Bourchier', 1995, 'cbourchierv@uiuc.edu');
insert into student (first_name, last_name, eag, email) values ('Jack', 'Bales', 2002, 'jbalesw@xrea.com');
insert into student (first_name, last_name, eag, email) values ('Kalie', 'Cadney', 2010, 'kcadneyx@addtoany.com');
insert into student (first_name, last_name, eag, email) values ('Hannis', 'Jahnke', 2007, 'hjahnkey@yahoo.co.jp');
insert into student (first_name, last_name, eag, email) values ('Julianna', 'Kryzhov', 2009, 'jkryzhovz@harvard.edu');
insert into student (first_name, last_name, eag, email) values ('Gran', 'Blaxland', 1987, 'gblaxland10@goodreads.com');
insert into student (first_name, last_name, eag, email) values ('Celene', 'Pearsey', 1999, 'cpearsey11@ameblo.jp');
insert into student (first_name, last_name, eag, email) values ('Gerhard', 'Jindrich', 2010, 'gjindrich12@topsy.com');
insert into student (first_name, last_name, eag, email) values ('Saloma', 'McSparran', 2007, 'smcsparran13@plala.or.jp');
insert into student (first_name, last_name, eag, email) values ('Christopher', 'Tilston', 1988, 'ctilston14@kickstarter.com');
insert into student (first_name, last_name, eag, email) values ('Irene', 'Sydry', 2013, 'isydry15@symantec.com');
insert into student (first_name, last_name, eag, email) values ('Peirce', 'Franklen', 2004, 'pfranklen16@rambler.ru');
insert into student (first_name, last_name, eag, email) values ('Cinderella', 'MacKenny', 2003, 'cmackenny17@wikimedia.org');
insert into student (first_name, last_name, eag, email) values ('Tracey', 'Heaford', 2008, 'theaford18@quantcast.com');
insert into student (first_name, last_name, eag, email) values ('Thekla', 'Wolfendell', 2006, 'twolfendell19@cdc.gov');
insert into student (first_name, last_name, eag, email) values ('Astrid', 'Demetr', 1985, 'ademetr1a@shop-pro.jp');
insert into student (first_name, last_name, eag, email) values ('Joyan', 'Alesin', 1993, 'jalesin1b@illinois.edu');
insert into student (first_name, last_name, eag, email) values ('Norman', 'Radmer', 2007, 'nradmer1c@woothemes.com');
insert into student (first_name, last_name, eag, email) values ('Brien', 'Ovenden', 1993, 'bovenden1d@bloomberg.com');
insert into student (first_name, last_name, eag, email) values ('Zebulen', 'Brusin', 2002, 'zbrusin1e@google.nl');
insert into student (first_name, last_name, eag, email) values ('Audy', 'Gerssam', 2012, 'agerssam1f@wp.com');
insert into student (first_name, last_name, eag, email) values ('Anny', 'McGlade', 1991, 'amcglade1g@github.io');
insert into student (first_name, last_name, eag, email) values ('Bell', 'Rummer', 2003, 'brummer1h@plala.or.jp');
insert into student (first_name, last_name, eag, email) values ('Justen', 'Berka', 2012, 'jberka1i@zdnet.com');
insert into student (first_name, last_name, eag, email) values ('Lars', 'Sheringham', 1996, 'lsheringham1j@networksolutions.com');
insert into student (first_name, last_name, eag, email) values ('Ashia', 'Preto', 1992, 'apreto1k@answers.com');
insert into student (first_name, last_name, eag, email) values ('Valentijn', 'Strathearn', 2006, 'vstrathearn1l@blinklist.com');
insert into student (first_name, last_name, eag, email) values ('Maxie', 'Grinstead', 2006, 'mgrinstead1m@wufoo.com');
insert into student (first_name, last_name, eag, email) values ('Salome', 'Dixsee', 2001, 'sdixsee1n@usgs.gov');
insert into student (first_name, last_name, eag, email) values ('Thibaut', 'Tejada', 1995, 'ttejada1o@ameblo.jp');
insert into student (first_name, last_name, eag, email) values ('Rube', 'Hubery', 2009, 'rhubery1p@oaic.gov.au');
insert into student (first_name, last_name, eag, email) values ('Wally', 'Giacoppoli', 2001, 'wgiacoppoli1q@bravesites.com');
insert into student (first_name, last_name, eag, email) values ('Addison', 'Petrenko', 2008, 'apetrenko1r@exblog.jp');
insert into student (first_name, last_name, eag, email) values ('Feodora', 'Fincham', 2010, 'ffincham1s@fc2.com');
insert into student (first_name, last_name, eag, email) values ('Dickie', 'Randlesome', 1992, 'drandlesome1t@phpbb.com');
insert into student (first_name, last_name, eag, email) values ('Stormi', 'Bramwich', 1990, 'sbramwich1u@multiply.com');
insert into student (first_name, last_name, eag, email) values ('Sigismund', 'Flowers', 1990, 'sflowers1v@wix.com');
insert into student (first_name, last_name, eag, email) values ('Dew', 'Fetter', 1992, 'dfetter1w@theatlantic.com');
insert into student (first_name, last_name, eag, email) values ('Free', 'Rihosek', 2013, 'frihosek1x@microsoft.com');
insert into student (first_name, last_name, eag, email) values ('Penny', 'Farrah', 1991, 'pfarrah1y@examiner.com');
insert into student (first_name, last_name, eag, email) values ('Ari', 'Birtwell', 2010, 'abirtwell1z@google.com.br');
insert into student (first_name, last_name, eag, email) values ('Karim', 'Iban', 1992, 'kiban20@surveymonkey.com');
insert into student (first_name, last_name, eag, email) values ('Mildrid', 'Sorby', 2010, 'msorby21@ucla.edu');
insert into student (first_name, last_name, eag, email) values ('Jeralee', 'Dunbobbin', 2005, 'jdunbobbin22@vinaora.com');
insert into student (first_name, last_name, eag, email) values ('Mordy', 'Gillies', 2008, 'mgillies23@goo.ne.jp');
insert into student (first_name, last_name, eag, email) values ('Maurene', 'McPartling', 2010, 'mmcpartling24@timesonline.co.uk');
insert into student (first_name, last_name, eag, email) values ('Jorrie', 'Burkert', 2007, 'jburkert25@tumblr.com');
insert into student (first_name, last_name, eag, email) values ('Wenda', 'Coots', 1989, 'wcoots26@wikipedia.org');
insert into student (first_name, last_name, eag, email) values ('Zed', 'Bishell', 1977, 'zbishell27@wired.com');
insert into student (first_name, last_name, eag, email) values ('Alexandra', 'Eake', 1996, 'aeake28@icio.us');
insert into student (first_name, last_name, eag, email) values ('Trina', 'Schohier', 2007, 'tschohier29@twitter.com');
insert into student (first_name, last_name, eag, email) values ('Zoe', 'Mabbe', 2008, 'zmabbe2a@angelfire.com');
insert into student (first_name, last_name, eag, email) values ('Archibald', 'Comellini', 2008, 'acomellini2b@artisteer.com');
insert into student (first_name, last_name, eag, email) values ('Tobey', 'Castell', 2008, 'tcastell2c@blogtalkradio.com');
insert into student (first_name, last_name, eag, email) values ('Faunie', 'McMichell', 2005, 'fmcmichell2d@behance.net');
insert into student (first_name, last_name, eag, email) values ('Katerine', 'Checklin', 2006, 'kchecklin2e@dagondesign.com');
insert into student (first_name, last_name, eag, email) values ('Beauregard', 'Levensky', 2009, 'blevensky2f@theguardian.com');
insert into student (first_name, last_name, eag, email) values ('Si', 'Pantone', 2004, 'spantone2g@whitehouse.gov');
insert into student (first_name, last_name, eag, email) values ('Rahal', 'Lory', 2000, 'rlory2h@people.com.cn');
insert into student (first_name, last_name, eag, email) values ('Filippo', 'Karle', 2011, 'fkarle2i@google.nl');
insert into student (first_name, last_name, eag, email) values ('Winnie', 'Carradice', 2004, 'wcarradice2j@clickbank.net');
insert into student (first_name, last_name, eag, email) values ('Georgena', 'Winscomb', 2002, 'gwinscomb2k@hao123.com');
insert into student (first_name, last_name, eag, email) values ('Leif', 'Bakey', 2004, 'lbakey2l@earthlink.net');
insert into student (first_name, last_name, eag, email) values ('Gan', 'Twinterman', 2006, 'gtwinterman2m@hao123.com');
insert into student (first_name, last_name, eag, email) values ('Germaine', 'Fido', 1992, 'gfido2n@ft.com');
insert into student (first_name, last_name, eag, email) values ('Staci', 'Nares', 2007, 'snares2o@wix.com');
insert into student (first_name, last_name, eag, email) values ('Haily', 'Snoxill', 1977, 'hsnoxill2p@ezinearticles.com');
insert into student (first_name, last_name, eag, email) values ('Madge', 'Pincked', 1992, 'mpincked2q@mail.ru');
insert into student (first_name, last_name, eag, email) values ('Lovell', 'Rapley', 2008, 'lrapley2r@google.ru');


-----------------------------------------------------------Teacher
insert into teacher (first_name, last_name, eag, email) values ('Gerardo', 'Kenewell', 1, 'gkenewell0@nsw.gov.au');
insert into teacher (first_name, last_name, eag, email) values ('Trevor', 'Wale', 2, 'twale1@issuu.com');
insert into teacher (first_name, last_name, eag, email) values ('Fredrika', 'Sisneros', 3, 'fsisneros2@aboutads.info');
insert into teacher (first_name, last_name, eag, email) values ('Florencia', 'Cradick', 4, 'fcradick3@japanpost.jp');
insert into teacher (first_name, last_name, eag, email) values ('Magdaia', 'De Filippi', 5, 'mdefilippi4@chicagotribune.com');
insert into teacher (first_name, last_name, eag, email) values ('Carmita', 'Brunet', 6, 'cbrunet5@rambler.ru');
insert into teacher (first_name, last_name, eag, email) values ('Marty', 'Stobbie', 7, 'mstobbie6@google.cn');
insert into teacher (first_name, last_name, eag, email) values ('Georgeanna', 'Seekings', 8, 'gseekings7@hp.com');
insert into teacher (first_name, last_name, eag, email) values ('Rebecca', 'Santello', 9, 'rsantello8@upenn.edu');
insert into teacher (first_name, last_name, eag, email) values ('Conchita', 'Kopman', 10, 'ckopman9@blogspot.com');
insert into teacher (first_name, last_name, eag, email) values ('Elwyn', 'Domokos', 11, 'edomokosa@ifeng.com');
insert into teacher (first_name, last_name, eag, email) values ('Adel', 'Gaither', 12, 'agaitherb@jimdo.com');
insert into teacher (first_name, last_name, eag, email) values ('Dannel', 'Fatkin', 13, 'dfatkinc@rakuten.co.jp');
insert into teacher (first_name, last_name, eag, email) values ('Ranee', 'Van Cassel', 14, 'rvancasseld@omniture.com');
insert into teacher (first_name, last_name, eag, email) values ('Olivette', 'Lecount', 15, 'olecounte@mediafire.com');
insert into teacher (first_name, last_name, eag, email) values ('Lucienne', 'Rulf', 16, 'lrulff@google.com');
insert into teacher (first_name, last_name, eag, email) values ('Essy', 'Di Carli', 17, 'edicarlig@nytimes.com');
insert into teacher (first_name, last_name, eag, email) values ('Haley', 'Kesten', 18, 'hkestenh@typepad.com');
insert into teacher (first_name, last_name, eag, email) values ('Gwendolen', 'East', 19, 'geasti@chron.com');
insert into teacher (first_name, last_name, eag, email) values ('Dannie', 'Livingston', 20, 'dlivingstonj@eepurl.com');
insert into teacher (first_name, last_name, eag, email) values ('Hurley', 'Goodbar', 21, 'hgoodbark@google.com.au');
insert into teacher (first_name, last_name, eag, email) values ('Melodee', 'O'' Finan', 22, 'mofinanl@dyndns.org');
insert into teacher (first_name, last_name, eag, email) values ('Ardys', 'Steen', 23, 'asteenm@senate.gov');
insert into teacher (first_name, last_name, eag, email) values ('Mac', 'Pritchitt', 24, 'mpritchittn@gravatar.com');
insert into teacher (first_name, last_name, eag, email) values ('Devlen', 'Koene', 25, 'dkoeneo@nationalgeographic.com');
insert into teacher (first_name, last_name, eag, email) values ('Harrie', 'Huster', 26, 'hhusterp@zdnet.com');
insert into teacher (first_name, last_name, eag, email) values ('Baudoin', 'Morriarty', 27, 'bmorriartyq@moonfruit.com');
insert into teacher (first_name, last_name, eag, email) values ('Yorgos', 'Cayet', 28, 'ycayetr@theguardian.com');
insert into teacher (first_name, last_name, eag, email) values ('Livvie', 'McAndrew', 29, 'lmcandrews@time.com');
insert into teacher (first_name, last_name, eag, email) values ('Isadora', 'Bolgar', 30, 'ibolgart@oaic.gov.au');
insert into teacher (first_name, last_name, eag, email) values ('Waverley', 'Goodred', 31, 'wgoodredu@newsvine.com');
insert into teacher (first_name, last_name, eag, email) values ('Nehemiah', 'Hagwood', 32, 'nhagwoodv@nifty.com');
insert into teacher (first_name, last_name, eag, email) values ('Miguel', 'Eliez', 33, 'meliezw@weather.com');
insert into teacher (first_name, last_name, eag, email) values ('Artie', 'Stinson', 34, 'astinsonx@wikipedia.org');
insert into teacher (first_name, last_name, eag, email) values ('Maxi', 'Bedham', 35, 'mbedhamy@washington.edu');
insert into teacher (first_name, last_name, eag, email) values ('Curry', 'Fulcher', 36, 'cfulcherz@toplist.cz');
insert into teacher (first_name, last_name, eag, email) values ('Billy', 'MacGiolla Pheadair', 37, 'bmacgiollapheadair10@tmall.com');
insert into teacher (first_name, last_name, eag, email) values ('Denny', 'Lockwood', 38, 'dlockwood11@marketwatch.com');
insert into teacher (first_name, last_name, eag, email) values ('Cleo', 'Alekseev', 39, 'calekseev12@free.fr');
insert into teacher (first_name, last_name, eag, email) values ('Baxy', 'Ife', 40, 'bife13@who.int');
insert into teacher (first_name, last_name, eag, email) values ('Rubie', 'Gherardini', 41, 'rgherardini14@statcounter.com');
insert into teacher (first_name, last_name, eag, email) values ('Nealson', 'McPolin', 42, 'nmcpolin15@google.de');
insert into teacher (first_name, last_name, eag, email) values ('Ennis', 'Bowmen', 43, 'ebowmen16@reuters.com');
insert into teacher (first_name, last_name, eag, email) values ('Perri', 'Hebden', 44, 'phebden17@github.io');
insert into teacher (first_name, last_name, eag, email) values ('Cleo', 'Lottrington', 45, 'clottrington18@telegraph.co.uk');
insert into teacher (first_name, last_name, eag, email) values ('Lorine', 'Beranek', 46, 'lberanek19@hugedomains.com');
insert into teacher (first_name, last_name, eag, email) values ('Doris', 'Tigner', 47, 'dtigner1a@uol.com.br');
insert into teacher (first_name, last_name, eag, email) values ('Grange', 'Ellerton', 48, 'gellerton1b@creativecommons.org');
insert into teacher (first_name, last_name, eag, email) values ('Mayer', 'Ritchings', 49, 'mritchings1c@tripod.com');
insert into teacher (first_name, last_name, eag, email) values ('Ky', 'Baldick', 50, 'kbaldick1d@usnews.com');
insert into teacher (first_name, last_name, eag, email) values ('Ira', 'Ainslee', 51, 'iainslee1e@netvibes.com');
insert into teacher (first_name, last_name, eag, email) values ('Rubie', 'Herion', 52, 'rherion1f@mac.com');
insert into teacher (first_name, last_name, eag, email) values ('Rorke', 'Tregale', 53, 'rtregale1g@smh.com.au');
insert into teacher (first_name, last_name, eag, email) values ('Gardener', 'Thorley', 54, 'gthorley1h@ifeng.com');
insert into teacher (first_name, last_name, eag, email) values ('Donnajean', 'Newlands', 55, 'dnewlands1i@webnode.com');
insert into teacher (first_name, last_name, eag, email) values ('Beatrice', 'Belly', 56, 'bbelly1j@reuters.com');
insert into teacher (first_name, last_name, eag, email) values ('Joshia', 'Slides', 57, 'jslides1k@patch.com');
insert into teacher (first_name, last_name, eag, email) values ('Brittani', 'Hardes', 58, 'bhardes1l@last.fm');
insert into teacher (first_name, last_name, eag, email) values ('Barb', 'Lofts', 59, 'blofts1m@feedburner.com');
insert into teacher (first_name, last_name, eag, email) values ('Jacques', 'Kitchingman', 60, 'jkitchingman1n@marketwatch.com');
insert into teacher (first_name, last_name, eag, email) values ('Oralle', 'McGettigan', 61, 'omcgettigan1o@tripadvisor.com');
insert into teacher (first_name, last_name, eag, email) values ('Krystle', 'Keary', 62, 'kkeary1p@ebay.co.uk');
insert into teacher (first_name, last_name, eag, email) values ('Kev', 'Jervis', 63, 'kjervis1q@jugem.jp');
insert into teacher (first_name, last_name, eag, email) values ('Myranda', 'Neilan', 64, 'mneilan1r@scribd.com');
insert into teacher (first_name, last_name, eag, email) values ('Laird', 'Garnham', 65, 'lgarnham1s@merriam-webster.com');
insert into teacher (first_name, last_name, eag, email) values ('Taite', 'Tethacot', 66, 'ttethacot1t@usgs.gov');
insert into teacher (first_name, last_name, eag, email) values ('Thane', 'Thurlby', 67, 'tthurlby1u@scientificamerican.com');
insert into teacher (first_name, last_name, eag, email) values ('Bernelle', 'Triswell', 68, 'btriswell1v@bing.com');
insert into teacher (first_name, last_name, eag, email) values ('Dayle', 'Freeberne', 69, 'dfreeberne1w@hibu.com');
insert into teacher (first_name, last_name, eag, email) values ('Eadmund', 'Nerne', 70, 'enerne1x@themeforest.net');
insert into teacher (first_name, last_name, eag, email) values ('Faunie', 'Farquhar', 71, 'ffarquhar1y@sogou.com');
insert into teacher (first_name, last_name, eag, email) values ('Siward', 'Celier', 72, 'scelier1z@dagondesign.com');
insert into teacher (first_name, last_name, eag, email) values ('Price', 'Adam', 73, 'padam20@uiuc.edu');
insert into teacher (first_name, last_name, eag, email) values ('Zulema', 'Wilflinger', 74, 'zwilflinger21@hao123.com');
insert into teacher (first_name, last_name, eag, email) values ('Anstice', 'Zannuto', 75, 'azannuto22@ning.com');
insert into teacher (first_name, last_name, eag, email) values ('Shandee', 'Pawelczyk', 76, 'spawelczyk23@hao123.com');
insert into teacher (first_name, last_name, eag, email) values ('Alina', 'Ditch', 77, 'aditch24@chicagotribune.com');
insert into teacher (first_name, last_name, eag, email) values ('Kristofer', 'Frame', 78, 'kframe25@mediafire.com');
insert into teacher (first_name, last_name, eag, email) values ('Shayna', 'Fearnside', 79, 'sfearnside26@bizjournals.com');
insert into teacher (first_name, last_name, eag, email) values ('Munroe', 'Shivell', 80, 'mshivell27@shop-pro.jp');
insert into teacher (first_name, last_name, eag, email) values ('Jacki', 'Lead', 81, 'jlead28@simplemachines.org');
insert into teacher (first_name, last_name, eag, email) values ('Hedda', 'Olyonov', 82, 'holyonov29@istockphoto.com');
insert into teacher (first_name, last_name, eag, email) values ('Caria', 'McMonnies', 83, 'cmcmonnies2a@upenn.edu');
insert into teacher (first_name, last_name, eag, email) values ('Ferdy', 'Sweetnam', 84, 'fsweetnam2b@mapquest.com');
insert into teacher (first_name, last_name, eag, email) values ('Peggy', 'Oaten', 85, 'poaten2c@forbes.com');
insert into teacher (first_name, last_name, eag, email) values ('Hester', 'Dictus', 86, 'hdictus2d@wufoo.com');
insert into teacher (first_name, last_name, eag, email) values ('Bank', 'Vedenisov', 87, 'bvedenisov2e@webeden.co.uk');
insert into teacher (first_name, last_name, eag, email) values ('Chrystel', 'Fochs', 88, 'cfochs2f@apache.org');
insert into teacher (first_name, last_name, eag, email) values ('Drusy', 'Faulkener', 89, 'dfaulkener2g@loc.gov');
insert into teacher (first_name, last_name, eag, email) values ('Jamison', 'Pawfoot', 90, 'jpawfoot2h@wikispaces.com');
insert into teacher (first_name, last_name, eag, email) values ('Brady', 'Windous', 91, 'bwindous2i@wufoo.com');
insert into teacher (first_name, last_name, eag, email) values ('Emlyn', 'Matiebe', 92, 'ematiebe2j@amazon.de');
insert into teacher (first_name, last_name, eag, email) values ('Avis', 'Snaddin', 93, 'asnaddin2k@unicef.org');
insert into teacher (first_name, last_name, eag, email) values ('Gayler', 'Van der Daal', 94, 'gvanderdaal2l@bluehost.com');
insert into teacher (first_name, last_name, eag, email) values ('Ethelyn', 'Ould', 95, 'eould2m@ucla.edu');
insert into teacher (first_name, last_name, eag, email) values ('Beale', 'Boow', 96, 'bboow2n@nifty.com');
insert into teacher (first_name, last_name, eag, email) values ('Jobye', 'Jakovijevic', 97, 'jjakovijevic2o@ycombinator.com');
insert into teacher (first_name, last_name, eag, email) values ('Gal', 'Fonteyne', 98, 'gfonteyne2p@ihg.com');
insert into teacher (first_name, last_name, eag, email) values ('Bartolomeo', 'Smyley', 99, 'bsmyley2q@g.co');
insert into teacher (first_name, last_name, eag, email) values ('Wilfrid', 'Antoszewski', 100, 'wantoszewski2r@mayoclinic.com');


-------------------------------subject

insert into subject (Subject) values ('Podstawy pedagogiki' );
insert into subject (Subject) values ('Filozofia humanistyczna');
insert into subject (Subject) values ('Psychologia twórczości i osobowości Eent');
insert into subject (Subject) values ('Teoria i praktyka animacji kultury ');
insert into subject (Subject) values ('Wprowadzenie do wiedzy o kulturze');
insert into subject (Subject) values ('Pedagogika kultury Zlopment');
insert into subject (Subject) values ('Media w edukacji Zlopment');
insert into subject (Subject) values ('Edukacja artystyczna');
insert into subject (Subject) values ('Podstawy marketingu');
insert into subject (Subject) values (' Socjologia kultury' );
insert into subject (Subject) values (' Zarządzania publiczne');
insert into subject (Subject) values (' Marketing sztuki');
insert into subject (Subject) values (' Zarządzanie działalnością kulturalną');
insert into subject (Subject) values (' Edukacja kulturalna');
insert into subject (Subject) values (' Metodyka działalności kulturalnej');
insert into subject (Subject) values (' Polityka kulturalna E');
insert into subject (Subject) values (' Prawodawstwo w działalności kulturalnej');
insert into subject (Subject) values (' Metodyka pracy animatora i menedżera kultury');
insert into subject (Subject) values (' Projekty kulturalne');
insert into subject (Subject) values (' Metodyka prowadzenia zajęć teatralnych');
insert into subject (Subject) values (' Metodyka prowadzenia zajęć tanecznych Zlopment');
insert into subject (Subject) values (' Projekt sceniczny');

--------------------course


insert into course (Course) values ('prawo');
insert into course (Course) values ('animacja');
insert into course (Course) values ('projekty');
insert into course (Course) values ('polityka');
insert into course (Course) values ('marketing');
